### ISSUE TITLE
Binding does not show up in Bindings section

### ISSUE THREAD

**Issue by freggel2401** [wildcs/oh3_tapocontrol#3]
Hello,
I have downloaded the TAPO Binding for version 3.1 and put the binding the addons folder. Afterwards I made sure that the access rights of the files are correct. I cann see in the logs: 

[l.internal.TapoControlHandlerFactory] - credentials not set

Which is obviously correct, because I cant't see the binding in the binding section. Restart has also no affect. As far as I understood I need to configure the credentials there. So did I miss a dependency or something, or is it just a bug?

Would be nice if you can help me solving the issue as I do have some of these devices and I am curious about about your work and really like to use it :)

Best,
Frerk

**Comment by wildcs** [comment]
you have to add thing manually if it's not downloaded with offficial OH-Addons
