### ISSUE TITLE
Tapo L930 error 

### ISSUE THREAD

**Issue by kylelliott** [wildcs/oh3_tapocontrol#6]
Keep getting this error have my p100 working which is amazing 

![image](https://github.com/wildcs/oh3_compiled-addons/assets/23058718/c2292148-918c-45d7-a387-3a7532a776a1)

**Comment by wildcs** [comment]
Got my L920 yesterday and run into same error. I already fixed it on my test-system already.
Have to upload a new compiled version but i want to fix another issue with P300-Devices first which will arrive today. 
So i think latest after the weekend this should be fixed. Maybe earlyer.

I'm afraid I'll have to buy most of the hardware to debug this issues. So I would be happy about some coffees :)

**Comment by wildcs** [comment]
Fixed.
Uploaded a new version. Use 4.0.4-Snapshot for 4.0.x
